# Generated by Django 3.0.6 on 2020-06-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_destination_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='name',
            new_name='Company_Name',
        ),
        migrations.AddField(
            model_name='destination',
            name='Full_names',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='Surname',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
